### ISSUE TITLE
Support embedding via GObject Introspection

### ISSUE THREAD

**Issue by mjakeman** [mjakeman/libweb-gtk#4]
Currently we use Gtkmm, which is great for writing, but is not very (at all?) bindable.

We have a few options:
 1. Create a manual C wrapper for the Gtkmm classes
 **2. Rewrite the library in pure C**
 3. Write a tool to automatically bind Gtkmm

Option 3 obviously depends on 1, and I'd rather avoid 2.

- [X] ~~Investigate using a Gtkmm class from C~~
- [X] ~~Look at generating GIR data for Gtkmm classes~~
- [X] ~~Create a demo using python or gjs~~

**Comment by tristan957** [comment]
@mjakeman one thing to look at might be using [cppgir](https://gitlab.com/mnauw/cppgir) instead of gtkmm. I am not sure how well it could help solve your problems though.

**Comment by mjakeman** [comment]
@tristan957 Thanks for the suggestion. I've tried to build it locally but unfortunately it seems the macOS/Windows support is lacking. There's also still the issue of not being bindable out of the box.

After some experimentation with gtkmm, I'm pretty confident binding that is out of the question.

The easiest option will probably be writing C-style GObject code after all

**Comment by tristan957** [comment]
Good luck with your project :). It will be really cool to use something that isn't WebKit!
